### ISSUE TITLE
Failed to start worker when server is booting 

### ISSUE THREAD

**Issue by kaikao** [kamisama/Fresque#50]
Hi, 

I'm trying to exec fresque command when sever reboot, to make every server I own will start workers automatically.

I'm using Amazon Linux, and put command "fresque start >> resque.log" to the instance settings "User Data"

The log file show me resque was stated failed, so I tried to change my command in user data to debug, "fresque test >> resque_debug.log" and looks everything fine, redid OK, database OK, etc

Just curious would you give me some advices?

Many thanks
Kai

**Comment by kamisama** [comment]
Usualy, it's a permission issue. 

Make sure that the "user" starting the workers on reboot has the right permissions

**Comment by kaikao** [comment]
@kamisama thanks for answer, I tried another way to create worker

this is the original way 
```
su -l 'ec2-user' -c './fresque start -q default &'
```

the new way
```
su -l ec2-user -c 'QUEUE=default APP_INCLUDE=/path/to/autoload.php COUNT=1 REDIS_BACKEND=localhost:6379 VVERBOSE=1 PREFIX=resque /usr/bin/php /path/to/php-resque-ex/bin/resque >> /path/to/resque.log 2>&1 &'
```

And it works now!

btw, fresque is really an awesome repo! thanks :)

**Comment by kamisama** [comment]
You could also try to start fresque with the `--user` option
