### ISSUE TITLE
Workers disappearing

### ISSUE THREAD

**Issue by rlweb** [kamisama/Fresque#52]
Probably not the best place to ask this but is there any way to get more debugging information my workers seem to stop every couple of days with nothing in the logs? Can't find much on the php-resque github either about this?

**Comment by kamisama** [comment]
Fresque does not log anything, logs are handled directly by php-resque itself.

What kind of 'stop' is it ? 

1 - Workers died, but is still registered in fresque
2 - Workers died, and disappear from fresque too
3 - Workers is known as died from fresque, but is still alive

You can check if your workers process are still alive with `ps aux | grep resque`. There should be one process for each worker.

You can also check the redis log `redis-cli monitor` for workers activities.

**Comment by rlweb** [comment]
It is three, since there is around 20 processes from running the ps command. I've kill'ed them all and restarted them via 'vendor/bin/fresque load'. Hopefully this might keep them going?

**Comment by kamisama** [comment]
Workers should never disappear from Fresque, unless you run the `fresque stop` command yourself.

You mention that the workers disappear every couple of days, and they're disappearing from Fresque only, workers are still running. Only explication is someone tried to run `fresque stop`, or something weird is clearing the fresque data from Redis.

You found 20 processes from the ps command. How many workers are still alive in Fresque ?

**Comment by rlweb** [comment]
Sorry for not replying back then! But yes the redis database was being flushed occasionally causing the issues. This can be closed now.
